outfile:main.o add.o file.o delete.o print.o count.o sort.o
	cc main.o add.o file.o delete.o print.o count.o sort.o -o outfile
main.o:main.c #single line comment
	cc -c main.c
add.o:add.c
	cc -c add.c
file.o:file.c
	cc -c file.c
delete.o:delete.c
	cc -c delete.c
print.o:print.c
	cc -c print.c
count.o:count.c
	cc -c count.c
sort.o:sort.c
	cc -c sort.c

