a.out : main.o insert.o search.o preorder.o inorder.o postorder.o minmax.o count.o delete.o
	cc main.o insert.o search.o preorder.o inorder.o postorder.o minmax.o count.o delete.o
	
main.o : main.c
	cc -c main.c
insert.o : insert.c
	cc -c insert.c
search.o : search.c
	cc -c search.c
preorder.o : preorder.c
	cc -c preorder.c
inorder.o : inorder.c
	cc -c inorder.c
postorder.o : postorder.c
	cc -c postorder.c
minmax.o : minmax.c
	cc -c minmax.c
count.o : count.c
	cc -c count.c
delete.o : delete.c
	cc -c delete.c
